### PR TITLE
Add authentication and simplified index.js

### PR DESCRIPTION
**Pull request by n44ps**
Hello,

I've been using your module inside my app and I needed to add authentication.
Also I didn't want to use dotenv inside the lib (having the choice to use what we want to load our API_KEY is better imo).

Thank you :)

### CODE REVIEW

**Comment by mebibou** [comment]
@N44PS yes you don't have to use dotenv, it's up to you to pass in which ever key when creating a `new BetaSeries('apiKey')`. Howerver the idea of having a setter was to not be able to change the apiKey later by having the key as a private property.

**Comment by mebibou** [comment]
@N44PS Please also fix the indent of your auth.js file (2 spaces everywhere) and write the object notations on multiple lines, i.e.

```
{
  a: 1,
  b: 2
}
```

thanks

**Comment by n44ps** [comment]
Alright I understand why you want it as a private property so I changed the way I required the module 

```
BetaSerie = new (require('betaseries'))(betaserie.api_key);
```

I reversed some changes and fixed the indent in auth.js
Thanks

**Comment by mebibou** [comment]
Looks good!

Now can you reword your commit messages following the contributing guidelines : https://github.com/mebibou/node-betaseries/blob/master/CONTRIBUTING.md#commit-message-format

If you're not used to this, look at my commit messages and you'll see how to do it :).

To reword with git:

``` shel
git rebase -i e10c1ede78c5624c9331b52a4b310bb32d0a3608
# replace pick with reword and save
# edit each commit message
```

**Comment by n44ps** [comment]
I tried to rename those commit messages, I ended up having : 

```
[detached HEAD 1caf8c6] feat(auth): create method for auth endpoint + refactor index.js
 2 files changed, 48 insertions(+), 29 deletions(-)
 create mode 100644 lib/betaseries/auth.js
 rewrite lib/betaseries/index.js (98%)
[detached HEAD 0a7cf5c] refactor(betaseries): change api initialization in shows + episodes
 2 files changed, 2 insertions(+), 2 deletions(-)
[detached HEAD 2261777] refactor(betaseries): change back to private properties + initializaton
 4 files changed, 38 insertions(+), 27 deletions(-)
 rewrite lib/betaseries/index.js (98%)
Successfully rebased and updated refs/heads/master.
```

I don't know why it didn't update :( Sorry I'm not using git that much !

**Comment by mebibou** [comment]
now you need to push your changes:

``` shel
git push -f
```

**Comment by n44ps** [comment]
Oh so simple yet necessary, it's done ! Thank you !

**Comment by mebibou** [comment]
Nice!
I pushed a new version of the module so that the travis CI tests are passing again.
Lastly before we can merge the PR:
1. Update your fork and PR to be up-to-date with the `master` branch
2. Create a test of your new `Auth` feature to show that it works

**Comment by n44ps** [comment]
Ok I think I did everything good, I tested myself the `Auth` test and it's all good.

**Comment by mebibou** [comment]
let's wait for the Travis CI build to finish, in the meantime can you verify the indent of the file? line 2 is not good

**Comment by n44ps** [comment]
Aye, sorry for this :)

**Comment by mebibou** [comment]
Nice.

Looking at the test file I have a few questions:
1. You are requiring a `crypto` module, but you haven't added it to the `devDependencies` in the `package.json` file
2. What is this login / id that you are using? are those your own credentials? if so, you need to setup those as the `process.env.BETASERIES_API_KEY`, i.e. in your `.env` file and then update the `README.md` file to explain what to do in order to have the `Auth` lib working

**Comment by n44ps** [comment]
1. The `crypto` module doesn't need to be installed via npm, it comes with NodeJS.
2. Those login / id are test logins listed here : http://www.betaseries.com/api/docs#comptes

Should I still update `README.md` ?

Edit : I commited a fix, the `episodes.all()` function needs a `token` param, the userId is optional but if you put null or an empty string, the api call returns an error.

**Comment by mebibou** [comment]
You don't have to update the `README` then if it's test accounts, nice. Also I reckon it would be better to put the login with the credentials in a helper file so that we do not have to copy-paste the code every time (so like `credentials.js` in test directory with a method to login / logout that returns the `token`)

**Comment by n44ps** [comment]
I created an other pull request and made the changes. I don't know why the Travis CI build failed there since I tested myself and it succeed.

**Comment by mebibou** [comment]
It's because you are asserting that the `token` of the `response` is equal to the one you got when you did the test, but a `token` has a living time so now it is not valid anymore.

You can only assert that the `token` is not null and you can keep the assertion on the id. So replace the `getToken` function in the `User` object by `getId` and put the assertion on this back?

**Comment by n44ps** [comment]
Weird because many times I found out the user token remain the same, anyway it's done !

**Pull request merged**
